spring:
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5433/productdb}
    username: ${PRODUCT_DB_USERNAME:postgres}
    password: ${PRODUCT_DB_PASSWORD:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/etiya-crm-project}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: http://test-eureka.etiya.com/eureka/
