spring:
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5433/notificationdb}
    username: ${NOTIFICATION_DB_USERNAME:postgres}
    password: ${NOTIFICATION_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: http://test-eureka.etiya.com/eureka/
