spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notificationdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
