spring:
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5433/orderdb}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka.etiya.com/eureka/
